### ISSUE TITLE
Add exception if there is no such command

### ISSUE THREAD

**Issue by 99stealth** [99stealth/aws-profile-manager#20]
The mistake was in the command `profile-swith`
```
aws-profile-manager profile-swith
Traceback (most recent call last):
  File "/Users/rbanakh/Library/Python/3.8/bin/aws-profile-manager", line 8, in <module>
    sys.exit(cli())
  File "/Users/rbanakh/Library/Python/3.8/lib/python/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/rbanakh/Library/Python/3.8/lib/python/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/rbanakh/Library/Python/3.8/lib/python/site-packages/click/core.py", line 1651, in invoke
    cmd_name, cmd, args = self.resolve_command(ctx, args)
  File "/Users/rbanakh/Library/Python/3.8/lib/python/site-packages/click/core.py", line 1698, in resolve_command
    cmd = self.get_command(ctx, cmd_name)
  File "/Users/rbanakh/Library/Python/3.8/lib/python/site-packages/aws_profile_manager/cli.py", line 33, in get_command
    with open(fn) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/rbanakh/Library/Python/3.8/lib/python/site-packages/aws_profile_manager/commands/profile-swith.py'
```

**Comment by 99stealth** [comment]
Done
